/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MiniProject;

import chap9.MySQLDB;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * @author LENOVO
 */
public class BankAccount extends javax.swing.JFrame {
    DefaultTableModel model;
    MySQLDB myDB;
    MyMoney mny;
    SavingAccount sv;
    FixedDepositAccount fx;
    int accountNumber, openAcc;
    String name, surname, accountType;
    double deposit, withdraw, balance;

    public BankAccount() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        myDB = new MySQLDB();
        sv = new SavingAccount();
        fx = new FixedDepositAccount();
//        SavingAccount sv = new SavingAccount();
        loadStudentData();

    }

    void loadStudentData() {
        try {
//            System.out.println("Hello");
            String sql = "SELECT * FROM `bank`";
            ArrayList<MyMoney> List = myDB.selectQuery1(sql);
            for (MyMoney i : List
            ) {
                System.out.println("Hello");
                String[] rowData = {String.valueOf(i.getAccountNumber()), i.getName(), i.getSurname(), i.getAccountType(), String.valueOf(i.getDeposit()), String.valueOf(i.getWithdraw()), String.valueOf(i.getBalance())};
//                String[] rowData = {id, name, surname};
                model.addRow(rowData);
                jTable1.setModel(model);
            }

        } catch (Exception e) {
            System.out.println("5555555" + e.getMessage());
        }
    }

    /**
     * Creates new form Money
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAccNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtOpen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDeposit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWithdraw = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "account number ", "์Name", "surname", "account type ", "deposit", "withdraw", "balance"
                }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input  Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("เลขบัญชี");

        txtAccNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAccNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNumActionPerformed(evt);
            }
        });
        txtAccNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccNumKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ชื่อ");

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("นามสกุล");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ประเภทบัญชี");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("เปิดบัญชี");

        txtOpen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpenActionPerformed(evt);
            }
        });
        txtOpen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOpenKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("บาท");

        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"SavingAccount", "FixedDepositAccount"}));
        cbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(5, 5, 5)
                                                .addComponent(txtOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(34, 34, 34))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGap(5, 5, 5)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                                                                                .addComponent(txtSurname))))))
                                                        .addGap(18, 18, 18))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input  Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ฝาก");

        txtDeposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepositKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ถอน");

        txtWithdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ยอดคงเหลือ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("บาท");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("บาท");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("บาท");

        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        buttonGroup1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jRadioButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(85, 85, 85)
                                                                .addComponent(jLabel5))
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                                        .addComponent(txtBalance))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel11)
                                        .addComponent(jRadioButton4))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel14)))
                                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 219, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAdd)
                                        .addComponent(btnDelete)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnExit))
                                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(117, 117, 117))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addComponent(btnAdd)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnDelete)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnUpdate)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnExit))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Account Detail");
        jPanel1.getAccessibleContext().setAccessibleDescription("");
        jPanel2.getAccessibleContext().setAccessibleName("555555");

        pack();
    }// </editor-fold>

    private void txtAccNumKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        String accountNumber = txtAccNum.getText();
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String AccountType = (String) cbxType.getSelectedItem();
        String deposit = txtDeposit.getText();
        String withdraw = txtWithdraw.getText();
        String balance = txtBalance.getText();
        String openAcc = txtOpen.getText();
        if (AccountType == "SavingAccount") {
            if (Integer.parseInt(openAcc) == 100) {
                System.out.println(openAcc);
                if (jRadioButton3.isSelected()) {
                    sv.deposit(Double.parseDouble(deposit));
                    double v = Double.parseDouble(deposit) + Double.parseDouble(openAcc);
                    System.out.println(v);
                    withdraw = String.valueOf(0);
                    balance = String.valueOf(v);
                    sv.printDetails();
                    txtBalance.setText(balance);
                    String[] rowData = {accountNumber, name, surname, AccountType, deposit, withdraw, balance};

                    String sql = "INSERT INTO `bank`(`account_number`, `name`, `surname`, `account_type`, `deposit`, `withdraw`, `balance`) VALUES " +
                            "('" + accountNumber + "','" + name + "','" + surname + "','" + AccountType + "','" + deposit + "','" + withdraw + "','" + balance + "')";
                    int row = myDB.creatUpdateDelete(sql);
                    model.addRow(rowData);
                    System.out.println(row);
                } else if (jRadioButton4.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "No");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Noooooooooooooo");

            }
//


        } else {
            if (Integer.parseInt(openAcc) == 1000) {
                System.out.println(openAcc);
                if (jRadioButton3.isSelected()) {
                    double v = Double.parseDouble(deposit) + Double.parseDouble(openAcc);
                    System.out.println(v);
                    fx.deposit(v);
                    withdraw = String.valueOf(0);
                    balance = String.valueOf((v));
                    fx.printDetails();
                    txtBalance.setText(balance);
                    String[] rowData = {accountNumber, name, surname, AccountType, deposit, withdraw, balance};

                    String sql = "INSERT INTO `bank`(`account_number`, `name`, `surname`, `account_type`, `deposit`, `withdraw`, `balance`) VALUES " +
                            "('" + accountNumber + "','" + name + "','" + surname + "','" + AccountType + "','" + deposit + "','" + withdraw + "','" + balance + "')";
                    int row = myDB.creatUpdateDelete(sql);
                    model.addRow(rowData);
                    System.out.println(row);
                } else if (jRadioButton4.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "No");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Noooooooooooooo");

            }
        }
        clearText();

    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(row, 0).toString();
        String sql = "DELETE FROM BANK WHERE `account_number` = '" + id + "'";
        int delRow = myDB.creatUpdateDelete(sql);

        if (delRow > 0) {
            model.removeRow(row);
            clearText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No delete");
        }
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int select = 0;
        String accountNumber, name, surname, AccountType, deposit, withdraw, balance;
        String name_upd, surname_upd, AccountType_upd, deposit_upd, withdraw_upd, balance_upd;
//        String name_upd, surname_upd;
        if (jTable1.getSelectedRow() >= 0) {
            select = jTable1.getSelectedRow();
            accountNumber = jTable1.getValueAt(select, 0).toString();
            name_upd = txtName.getText();
            surname_upd = txtSurname.getText();
            AccountType_upd = (String) cbxType.getSelectedItem();
            deposit_upd = txtDeposit.getText();
            withdraw_upd = txtWithdraw.getText();
            balance_upd = txtBalance.getText();

            if (AccountType_upd == "SavingAccount") {

                if (jRadioButton3.isSelected()) {
                    withdraw_upd = String.valueOf(0);
                    double v = Double.parseDouble(balance_upd) + Double.parseDouble(deposit_upd);
                    sv.deposit(v);
                    balance_upd = String.valueOf((v));
                    txtBalance.setText(balance_upd);
                    sv.printDetails();
                } else if (jRadioButton4.isSelected()) {
                    deposit_upd = String.valueOf(0);
                    System.out.println(balance_upd);
                    System.out.println(withdraw_upd);
                    double v = Double.parseDouble(balance_upd) - Double.parseDouble(withdraw_upd);
                    sv.withdraw(v);
                    txtBalance.setText(String.valueOf(v));
                    balance_upd = String.valueOf(v);
                    sv.printDetails();
                }
                String sql = "UPDATE `bank` SET `name` = '" + name_upd + "', `surname` = '" + surname_upd + "',`account_type` = '" + AccountType_upd + "', `deposit` = '" + deposit_upd + "',`withdraw` = '" + withdraw_upd + "', `balance` = '" + balance_upd + "' WHERE `bank`.`account_number` = '" + accountNumber + "'";
                int Row = myDB.creatUpdateDelete(sql);
                if (Row > 0) {
                    jTable1.setValueAt(name_upd, select, 1);
                    jTable1.setValueAt(surname_upd, select, 2);
                    jTable1.setValueAt(AccountType_upd, select, 3);
                    jTable1.setValueAt(deposit_upd, select, 4);
                    jTable1.setValueAt(withdraw_upd, select, 5);
                    jTable1.setValueAt(balance_upd, select, 6);
                } else {
                    System.out.println(" ");
                }
            } else {
                if (jRadioButton3.isSelected()) {
                    if (Double.parseDouble(deposit_upd) >= 500) {

                        withdraw_upd = String.valueOf(0);
                        fx.deposit(Double.parseDouble(deposit_upd));
                        double v = Double.parseDouble(balance_upd) + Double.parseDouble(deposit_upd);
                        balance_upd = String.valueOf((v));
                        txtBalance.setText(balance_upd);
                        fx.printDetails();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "5000BRO");

                    }
                } else if (jRadioButton4.isSelected()) {
                    deposit_upd = String.valueOf(0);
                    fx.withdraw(Double.parseDouble(withdraw_upd));
                    double v = Double.parseDouble(balance_upd) - Double.parseDouble(withdraw_upd);
                    balance_upd = String.valueOf((v));
                    txtBalance.setText(balance_upd);
                    fx.printDetails();
                }
                String sql = "UPDATE `bank` SET `name` = '" + name_upd + "', `surname` = '" + surname_upd + "',`account_type` = '" + AccountType_upd + "', `deposit` = '" + deposit_upd + "',`withdraw` = '" + withdraw_upd + "', `balance` = '" + balance_upd + "' WHERE `bank`.`account_number` = '" + accountNumber + "'";
                int Row = myDB.creatUpdateDelete(sql);
                if (Row > 0) {
                    jTable1.setValueAt(name_upd, select, 1);
                    jTable1.setValueAt(surname_upd, select, 2);
                    jTable1.setValueAt(AccountType_upd, select, 3);
                    jTable1.setValueAt(deposit_upd, select, 4);
                    jTable1.setValueAt(withdraw_upd, select, 5);
                    jTable1.setValueAt(balance_upd, select, 6);
                } else {
                    System.out.println(" ");
                }
            }

        } else {
            System.out.println(" ");
        }
        clearText();

    }

    private void clearText() {
        txtAccNum.setText("");
        txtName.setText("");
        txtSurname.setText("");
        txtDeposit.setText("");
        txtWithdraw.setText("");
        txtBalance.setText("");
    }

    private void txtDepositKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }

    private void cbxTypeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtOpenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtAccNumActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtOpenKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }

    }

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String accountNumber = (String) jTable1.getValueAt(row, 0);
            String name = (String) jTable1.getValueAt(row, 1);
            String surname = (String) jTable1.getValueAt(row, 2);
            String accountType = (String) jTable1.getValueAt(row, 3);
            String deposit = (String) jTable1.getValueAt(row, 4);
            String withdraw = (String) jTable1.getValueAt(row, 5);
            String balance = (String) jTable1.getValueAt(row, 6);
            txtAccNum.setText(accountNumber);
            txtName.setText(name);
            txtSurname.setText(surname);
            txtBalance.setText(balance);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOpen;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtWithdraw;
    // End of variables declaration
}
