package MiniProject;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import chap9.MySQLDB;
import com.sun.jdi.Value;

import javax.swing.JOptionPane;

/**
 * @author LENOVO
 */
public class PhotoLap extends javax.swing.JFrame {
    MySQLDB myDB;

    /**
     * Creates new form PhotoColorLap
     */
    public PhotoLap() {
        myDB = new MySQLDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMini = new javax.swing.JCheckBox();
        cbJumbo = new javax.swing.JCheckBox();
        cbSuper = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spMini = new javax.swing.JSpinner();
        spJunbo = new javax.swing.JSpinner();
        spSuper = new javax.swing.JSpinner();
        btnClear = new javax.swing.JButton();
        btnCount = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Anakotmai Bold", 0, 12)); // NOI18N
        jLabel1.setText("ร้านถ่ายภาพ");

        jLabel2.setFont(new java.awt.Font("Anakotmai Bold", 0, 12)); // NOI18N
        jLabel2.setText("ร้านถ่ายภาพ");

        jLabel3.setText("Jumbo");

        jLabel4.setText("Mini");

        jLabel5.setText("Super");

        jLabel6.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel6.setText("จำนวน");

        jLabel7.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel7.setText("รหัส");

        jLabel8.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel8.setText("จำนวน");

        btnClear.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCount.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        btnCount.setText("คำนวณราคา");
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        btnExit.setText("Exit");

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        jLabel9.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel9.setText("จำนวน");

        jLabel10.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel10.setText("นามสกุล");

        jLabel11.setFont(new java.awt.Font("Anakotmai Medium", 0, 12)); // NOI18N
        jLabel11.setText("ชื่อ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(251, 251, 251)
                                                .addComponent(btnExit))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(txtId)
                                                                                .addComponent(txtName)
                                                                                .addComponent(txtSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(cbSuper)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(cbJumbo)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(cbMini)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(spMini)
                                                        .addComponent(spJunbo)
                                                        .addComponent(spSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnCount)
                                                        .addComponent(btnClear))))
                                .addContainerGap(126, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(273, 273, 273)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(381, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(spMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnCount))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(spJunbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(spSuper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbMini)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cbJumbo)
                                                        .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbSuper)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5)
                                                                .addComponent(btnClear)))))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnExit)
                                .addGap(46, 46, 46))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(jLabel9)
                                        .addContainerGap(340, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {
        String id = txtId.getText();
        String name = txtName.getText();
        String surname = txtSurname.getText();
        int total = 0, bath = 0, count = 0, spCount1 = 0, spCount2 = 0, spCount3 = 0, mnb = 0, jbb = 0, spb = 0;
        String type = " ";
        String result1 = " ", result2 = " ", result3 = " ";
        int mini = (int) spMini.getValue();
        int jumbo = (int) spJunbo.getValue();
        int superr = (int) spSuper.getValue();
        if (cbMini.isSelected()) {
            spCount1 = mini;
            type = "mini";
            bath = 7;
            mnb = spCount1 * bath;
            count++;
            result1 = count + ". " + type + "(" + spCount1 + "x" + bath + ")" + "=" + mnb + "bath\n";
        }
        if (cbJumbo.isSelected()) {
            spCount2 = jumbo;
            type = "jumbo";
            bath = 10;
            jbb = spCount2 * bath;
            count++;
            result2 = count + ". " + type + "(" + spCount2 + "x" + bath + ")" + "=" + jbb + "bath\n";

        }
        if (cbSuper.isSelected()) {
            spCount3 = superr;
            type = "super";
            bath = 30;
            spb = spCount3 * bath;
            count++;
            result3 = count + ". " + type + "(" + spCount3 + "x" + bath + ")" + "=" + spb + "bath\n";

        }
        total = mnb + jbb + spb;
        System.out.println(total);
        if (total >= 1000) {
            txtResult.setText(result1 + result2 + result3 + "Total Price :" + total + "bath \n" + "Promotion: Umbrella(1)");
            String sql = "INSERT INTO `photolap`(`id`, `name`, `surname`, `num_mini`, `num_jumbo`, `num_super`, `total` ,`promotion` ) VALUES " +
                    "('" + id + "','" + name + "','" + surname + "','" + spCount1 + "','" + spCount2 + "','" + spCount3 + "','" + total + "','  Umbrella(1)  ')";
            int row = myDB.creatUpdateDelete(sql);
        } else if (total >= 500) {
            txtResult.setText(result1 + result2 + result3 + "Total Price :" + total + "bath \n" + "Promotion: Glass(1)");
            String sql = "INSERT INTO `photolap`(`id`, `name`, `surname`, `num_mini`, `num_jumbo`, `num_super`, `total` ,`promotion` ) VALUES " +
                    "('" + id + "','" + name + "','" + surname + "','" + spCount1 + "','" + spCount2 + "','" + spCount3 + "','" + total + "','  Glass(1)  ')";
            int row = myDB.creatUpdateDelete(sql);
        } else {
            txtResult.setText(result1 + result2 + result3 + "Total Price :" + total + "bath \n" + "Promotion: Pen(1)");
            String sql = "INSERT INTO `photolap`(`id`, `name`, `surname`, `num_mini`, `num_jumbo`, `num_super`, `total` ,`promotion` ) VALUES " +
                    "('" + id + "','" + name + "','" + surname + "','" + spCount1  + "','" + spCount2 + "','" + spCount3 + "','" + total + "','  Pen(1)  ')";
            int row = myDB.creatUpdateDelete(sql);
        }
        clearText();


    }
    void clearText() {
        txtId.setText(" ");
        txtName.setText("");
        txtSurname.setText(" ");
        spMini.setValue(0);
        spJunbo.setValue(0);
        spSuper.setValue(0);
        cbMini.setSelected(false);
        cbSuper.setSelected(false);
        cbJumbo.setSelected(false);
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         txtId.setText(" ");
        txtName.setText("");
        txtSurname.setText(" ");
        txtResult.setText(" ");
        spMini.setValue(0);
        spJunbo.setValue(0);
        spSuper.setValue(0);
        cbMini.setSelected(false);
        cbSuper.setSelected(false);
        cbJumbo.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhotoLap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhotoLap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhotoLap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhotoLap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotoLap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbJumbo;
    private javax.swing.JCheckBox cbMini;
    private javax.swing.JCheckBox cbSuper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spJunbo;
    private javax.swing.JSpinner spMini;
    private javax.swing.JSpinner spSuper;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration
}
